server:
  port: 8002

spring:
  datasource:
    url: ENC(CME3/hc/qLgRu1/yBUEvBM70vwxhkTbag+0NOJuen2wco8Ft1kMVQWxw0tksc7e8LTK3FE2qxv/W+pBJ15DLkDmHEWMKELVNmVDOS8V3sOx3e6y42hZpjDKlYxHlP2JoFCA6e+3JrpautIsoqEdnng==)
    username: ENC(wkNqgPR+zw2ev6kDzUJaoA==)
    password: ENC(CioE8/kTjiNovsPoDSPQAbI87EYmmP1t)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

#yml 암호화 yml 설정
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

notification:
  mattermost:
    enabled: true
    webhook-url: ENC(vxKUrqtENMyaPPK5Jqf2P58689oKo66nSRv9KRjtmil5LFY6ns8m7ZzqFFJYe00+tdOCRgRyJY7SYByqxvrE1RpKd7ZiMPLf)
    channel: # ?? ??? ??? ?? ?? ??? ??? ?? ? ????
    pretext: UserService Error # attachments? ??? ??? ?? ?? ??? ??
    #    color: # attachment? ?? ??? ??. default=red
    author-name: mmSender # attachment? ??? ??? ??
    author-icon: https://mattermost.com/wp-content/uploads/2022/02/icon.png # author-icon ??? ?? ???? url??
#    footer: # attachment? ??? ?? ??. default=?? ??
