server:
  port: 8002

spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/show_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: yyhj7424
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ENC(CME3/hc/qLgRu1/yBUEvBM70vwxhkTbag+0NOJuen2wco8Ft1kMVQWxw0tksc7e8LTK3FE2qxv/W+pBJ15DLkDmHEWMKELVNmVDOS8V3sOx3e6y42hZpjDKlYxHlP2JoFCA6e+3JrpautIsoqEdnng==)
#    username: ENC(wkNqgPR+zw2ev6kDzUJaoA==)
#    password: ENC(CioE8/kTjiNovsPoDSPQAbI87EYmmP1t)
#    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: DEV-CRAWLING-SERVICE

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
#      group-id: crawling-service-1 # ex) user-service-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      topic: dev-show # 데이터를 퍼블리싱할 곳의 토픽 ex) dev-user
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

web-driver:
  chrome:
    driver-path: /Users/jongseong/dev/ssafy/2nd/free-project/crawling_service/be/nnz-crawling/chromedriver


#yml 암호화 yml 설정
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

notification:
  mattermost:
    enabled: true
    webhook-url: ENC(vxKUrqtENMyaPPK5Jqf2P58689oKo66nSRv9KRjtmil5LFY6ns8m7ZzqFFJYe00+tdOCRgRyJY7SYByqxvrE1RpKd7ZiMPLf)
    channel: # ?? ??? ??? ?? ?? ??? ??? ?? ? ????
    pretext: Dev CrawlingService Error # attachments? ??? ??? ?? ?? ??? ??
    #    color: # attachment? ?? ??? ??. default=red
    author-name: mmSender # attachment? ??? ??? ??
    author-icon: https://mattermost.com/wp-content/uploads/2022/02/icon.png # author-icon ??? ?? ???? url??
#    footer: # attachment? ??? ?? ??. default=?? ??
