server:
  port: 8084
spring:
  application:
    name: DEV-TAG-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(10aUuPU1LkpGUa67GY3ftGHQ+lpr1ULpXY0CNPJv8vXPhuT+/YLca2wuYNH+Y1yPlVyf3Hx8wF9+enItfNDa9mYytGyxvM6RWTHMsy0yKUqkvUTZZSjHaWTNRo3PNGisRGJXvQqBF21NpWw5Xv9WrA==)
    username: ENC(r9+5XUFLaQJxTySGqeygbA==)
    password: ENC(mqPyqNcjpm9xW79zMYa9pzmuOdmwHnvE)

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      #      ddl-auto: none
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
  kafka:
    prefix: dev-
    bootstrap-servers: http://k8b207.p.ssafy.io:29092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  redis:
    host: ENC(+9h0Soa0ASvurYPtju+G9Q==)
    port: 6379
    password: ENC(LYaFkmNEuCOhq2K1ci5CbbHAZyS8Pd62)
  cache:
    type: redis

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ENC(aNWlQEmNM4GnFa8SLISQ2XffFZfsIGzQ0WuQqiPWYUHzkb6zSn3HEkDFpnry2XtlwrJx22vcfYM=)

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

notification:
  mattermost:
    enabled: false
    webhook-url: ENC(L3DJfaOz0UEVz7FUMA5KHhLRhpQn+ehd/fCjXZWie7VdNDRNe/w/Z4pc10tfPuylwx0geLtilsCFpPbpANICJS/D7U+6QFSN)
    channel: # ?? ??? ??? ?? ?? ??? ??? ?? ? ????
    pretext: occur error # attachments? ??? ??? ?? ?? ??? ??
    #    color: # attachment? ?? ??? ??. default=red
    author-name: mmSender # attachment? ??? ??? ??
    author-icon: https://mattermost.com/wp-content/uploads/2022/02/icon.png # author-icon ??? ?? ???? url??
#    footer: # attachment? ??? ?? ??. default=?? ??
