server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: DEV-GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: DEV-SHOW-SERVICE
          uri: lb://DEV-SHOW-SERVICE
          predicates:
            - Path=/show-service/**
        - id: DEV_USER_SERVICE
          uri: lb://DEV-USER-SERVICE
          predicates:
            - Path=/user-service/**
        - id: DEV-NANUM-SERVICE
          uri: lb://DEV-NANUM-SERVICE
          predicates:
            - Path=/nanum-service/**
        - id: DEV-TAG-SERVICE
          uri: lb://DEV-TAG-SERVICE
          predicates:
            - Path=/tag-service/**