// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIVVHQYg6EvN0ipvB2HnAx3PKQvsm3mjU',
    appId: '1:175235208758:web:6b561e521646f3e681ea97',
    messagingSenderId: '175235208758',
    projectId: 'naneozoo',
    authDomain: 'naneozoo.firebaseapp.com',
    storageBucket: 'naneozoo.appspot.com',
    measurementId: 'G-38T1WHVT4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAuWqHRzLF2Rx0DzYOiWuo07llf3zrVtA',
    appId: '1:175235208758:android:0373d542e41dde7981ea97',
    messagingSenderId: '175235208758',
    projectId: 'naneozoo',
    storageBucket: 'naneozoo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcIPFldFc34wS1QKX_iMdCOdyjMON3B90',
    appId: '1:175235208758:ios:bdb7f58f74e4687481ea97',
    messagingSenderId: '175235208758',
    projectId: 'naneozoo',
    storageBucket: 'naneozoo.appspot.com',
    iosClientId: '175235208758-3agjf92m00dn1lqbrbdffjldo4l9ogps.apps.googleusercontent.com',
    iosBundleId: 'com.nnz.nnz',
  );
}
